[alembic]
script_location = alembic
file_template = %%(rev)s_%%(slug)s
prepend_sys_path = src
sqlalchemy.url = postgresql+asyncpg://user:password@localhost:5432/cng_compliance

[post_write_hooks]

[logging]
default_level = INFO
