environment             = "production"
primary_region          = "ap-south-1"
secondary_region        = "ap-southeast-1"
primary_vpc_cidr        = "10.100.0.0/16"
secondary_vpc_cidr      = "10.200.0.0/16"
db_name                 = "cng_compliance_prod"
db_username             = "cng_prod_admin"
db_password_secret_arn  = "arn:aws:secretsmanager:ap-south-1:123456789012:secret:cng/prod/db-password"
